## Deliverable 2. Create a Customer Travel Destinations Map.

In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import matplotlib.pyplot as plt
import numpy as np
# Import API key
from config import g_key

In [6]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../WD/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,susanville,US,40.4163,-120.6530,66.20,15,1,11.50,clear sky
1,1,bluff,NZ,-46.6000,168.3333,57.99,57,100,21.99,overcast clouds
2,2,tuktoyaktuk,CA,69.4541,-133.0374,8.60,92,90,20.71,snow
3,3,solnechnyy,RU,50.7214,136.6319,40.08,37,14,3.94,few clouds
4,4,mataura,NZ,-46.1927,168.8643,57.99,57,100,23.00,overcast clouds

In [7]:
city_data_df['Max temp'].describe()

count    1864.000000
mean       58.743557
std        21.169120
min       -16.490000
25%        42.800000
50%        64.295000
75%        76.620000
max        96.800000
Name: Max temp, dtype: float64

In [8]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [9]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
clean_df = city_data_df.loc[(city_data_df["Max temp"] <= max_temp) & \
                                       (city_data_df["Max temp"] >= min_temp)]
                                      
clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max temp,Humidity,Cloudiness,Wind Speed,Current Description
11,11,nhamunda,BR,-2.1861,-56.7131,75.42,93,17,2.59,few clouds
13,13,vaini,TO,-21.2000,-175.2000,77.00,69,20,11.50,few clouds
19,19,flinders,AU,-34.5833,150.8552,82.00,78,75,11.50,broken clouds
20,20,arraial do cabo,BR,-22.9661,-42.0278,75.54,73,53,10.96,broken clouds
30,30,atuona,PF,-9.8000,-139.0333,80.13,79,76,8.55,light rain
32,32,codo,BR,-4.4553,-43.8856,76.35,85,72,2.57,broken clouds
39,39,cabo san lucas,MX,22.8909,-109.9124,86.00,21,1,17.27,clear sky
40,40,saint-philippe,RE,-21.3585,55.7679,77.00,69,0,5.75,clear sky
46,46,tiarei,PF,-17.5333,-149.3333,86.00,70,20,12.66,few clouds
62,62,hithadhoo,MV,-0.6000,73.0833,83.08,75,40,16.08,scattered clouds

In [10]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                541
City                   541
Country                540
Lat                    541
Lng                    541
Max temp               541
Humidity               541
Cloudiness             541
Wind Speed             541
Current Description    541
dtype: int64

In [11]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df.dropna()

,City_ID,City,Country,Lat,Lng,Max temp,Humidity,Cloudiness,Wind Speed,Current Description
11,11,nhamunda,BR,-2.1861,-56.7131,75.42,93,17,2.59,few clouds
13,13,vaini,TO,-21.2000,-175.2000,77.00,69,20,11.50,few clouds
19,19,flinders,AU,-34.5833,150.8552,82.00,78,75,11.50,broken clouds
20,20,arraial do cabo,BR,-22.9661,-42.0278,75.54,73,53,10.96,broken clouds
30,30,atuona,PF,-9.8000,-139.0333,80.13,79,76,8.55,light rain
...,...,...,...,...,...,...,...,...,...,...
1838,1838,praya,CV,14.9215,-23.5087,77.00,33,0,18.41,clear sky
1839,1839,da nang,VN,16.0678,108.2208,80.60,74,40,3.67,scattered clouds
1845,1845,goure,NE,13.9835,10.2704,80.01,9,7,5.99,clear sky
1847,1847,finschhafen,PG,-6.6024,147.8681,85.69,70,21,4.59,few clouds
1857,1857,gilbues,BR,-9.8317,-45.3439,76.10,60,31,2.44,scattered clouds

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max temp,Current Description,Lat,Lng,Hotel Name
11,nhamunda,BR,75.42,few clouds,-2.1861,-56.7131,
13,vaini,TO,77.00,few clouds,-21.2000,-175.2000,
19,flinders,AU,82.00,broken clouds,-34.5833,150.8552,
20,arraial do cabo,BR,75.54,broken clouds,-22.9661,-42.0278,
30,atuona,PF,80.13,light rain,-9.8000,-139.0333,
32,codo,BR,76.35,broken clouds,-4.4553,-43.8856,
39,cabo san lucas,MX,86.00,clear sky,22.8909,-109.9124,
40,saint-philippe,RE,77.00,clear sky,-21.3585,55.7679,
46,tiarei,PF,86.00,few clouds,-17.5333,-149.3333,
62,hithadhoo,MV,83.08,scattered clouds,-0.6000,73.0833,

In [13]:
hotel_df.isna().sum()

City                   0
Country                1
Max temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

###  Notes: I reset the index, so that the loop prints from 1,2 .... rather than random index numbers

In [21]:
# hotel_df=hotel_df.reset_index()

In [16]:
# Iterate through the Dataframe.

for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    print(index)
    # Add the latitude and longitude to the location key for the param dictonary
    params["location"] = f"{lat},{lng}"
    
    # use the search term" "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the json data from the search
    hotels = requests.get(base_url, params=params).json()
    #print(hotels)
    # Grab the first hotel from the results and store the name.
    try:
        
         print(index, hotels["results"][0]["name"])
         hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except(IndexError):
         print(index, "Hotel not found ......skipping.")
hotel_df.head(10)

11
11 Pousada Da Praia
13
13 Keleti Beach Resort
19
19 Shellharbour Resort & Conference Centre
20
20 Pousada Porto Praia
30
30 Villa Enata
32
32 Hotel Porto do Sol
39
39 Hotel Tesoro Los Cabos
40
40 Chambres d'hôte "La Trinité"
46
46 Le Rocher de Tahiti
62
62 Scoop Guest House
65
65 Bora-Bora Pearl Beach Resort & Spa
68
68 People ThankYou
69
69 Guest Hotel
75
75 Pension Paradis
77
77 Shandrani Beachcomber Resort & Spa
83
83 Krishna Sweets
86
86 Hotel Karysmã
89
89 Hondaafushi Island Resort
90
90 Atlantis Hotel
91
91 Taloa Heights
92
92 Mercure Padang
93
93 Tang Dynasty Lodge Kota Belud
102
102 Mitibkieta Annexe
107
107 Veranda Paul et Virginie Hotel & Spa
109
109 Restaurant Greedy Coco Lodge Majunga
111
111 Hotel not found ......skipping.
112
112 ZINGARA 76ft Catamaran, full crew-all included
114
114 Hotels in Lakshadweep Islands
115
115 Hospitality Carnarvon
117
117 Penginapan Kim
126
126 Days End Lodge
127
127 Quality Suites Vila Velha
129
129 Shanti Maurice Resort & Spa
133
133 Paradise Inn
135
135 Lorengau Harbourside Hotel
136
136 Hotel Praia Morena
140
140 Nusa Island Retreat
146

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [17]:
hotel_df.head(10)

,City,Country,Max temp,Current Description,Lat,Lng,Hotel Name
11,nhamunda,BR,75.42,few clouds,-2.1861,-56.7131,Pousada Da Praia
13,vaini,TO,77.00,few clouds,-21.2000,-175.2000,Keleti Beach Resort
19,flinders,AU,82.00,broken clouds,-34.5833,150.8552,Shellharbour Resort & Conference Centre
20,arraial do cabo,BR,75.54,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
30,atuona,PF,80.13,light rain,-9.8000,-139.0333,Villa Enata
32,codo,BR,76.35,broken clouds,-4.4553,-43.8856,Hotel Porto do Sol
39,cabo san lucas,MX,86.00,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
40,saint-philippe,RE,77.00,clear sky,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
46,tiarei,PF,86.00,few clouds,-17.5333,-149.3333,Le Rocher de Tahiti
62,hithadhoo,MV,83.08,scattered clouds,-0.6000,73.0833,Scoop Guest House

In [18]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df['Hotel Name'].value_counts()

                                                  505
Hospitality Carnarvon                               1
Shanti Maurice Resort & Spa                         1
Bora-Bora Pearl Beach Resort & Spa                  1
Hotel Karysmã                                       1
Hotel Tesoro Los Cabos                              1
Mercure Padang                                      1
Chambres d'hôte "La Trinité"                        1
Taloa Heights                                       1
Pousada Porto Praia                                 1
Paradise Inn                                        1
Nusa Island Retreat                                 1
Villa Enata                                         1
Atlantis Hotel                                      1
ZINGARA 76ft Catamaran, full crew-all included      1
Pousada Da Praia                                    1
Quality Suites Vila Velha                           1
Lorengau Harbourside Hotel                          1
Hondaafushi Island Resort                           1
Hotel Praia Morena                                  1
Scoop Guest House                                   1
Hotel Porto do Sol                                  1
Krishna Sweets                                      1
Veranda Paul et Virginie Hotel & Spa                1
Guest Hotel                                         1
Days End Lodge                                      1
Pension Paradis                                     1
Shellharbour Resort & Conference Centre             1
People ThankYou                                     1
Le Rocher de Tahiti                                 1
Mitibkieta Annexe                                   1
Penginapan Kim                                      1
Shandrani Beachcomber Resort & Spa                  1
Keleti Beach Resort                                 1
Restaurant Greedy Coco Lodge Majunga                1
Tang Dynasty Lodge Kota Belud                       1
Hotels in Lakshadweep Islands                       1
Name: Hotel Name, dtype: int64

In [19]:
clean_hotel_df=hotel_df[hotel_df['Hotel Name']!='']

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [21]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [22]:

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# 11b. Display thee figure
fig

Figure(layout=FigureLayout(height='420px'))